<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="LAPTOP-IT2D940V" failures="1" tests="1" name="Default test(failed)" time="3.389" errors="0" timestamp="2022-10-22T12:36:23 IST">
  <testcase classname="TestCases.FailedTest" name="verifyLoginLogoTest" time="0.044">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.verifyLoginLogoTest(FailedTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginLogoTest -->
  <testcase classname="TestCases.FailedTest" name="loginToApp1Test" time="0.0">
    <ignored/>
  </testcase> <!-- loginToApp1Test -->
  <testcase classname="TestCases.FailedTest" name="verifyTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleTest -->
  <testcase classname="TestCases.FailedTest" name="verifyUrlTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUrlTest -->
  <testcase classname="TestCases.FailedTest" name="loginApp2Test" time="0.0">
    <ignored/>
  </testcase> <!-- loginApp2Test -->
  <testcase classname="TestCases.FailedTest" name="verifyBotLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyBotLogoTest -->
</testsuite> <!-- Default test(failed) -->
